config/routes.rb
ImpressJsApp::Application.routes.draw do
  get "password_resets/new"

  match 'download' => 'presentation#download'
  match 'components' => 'presentation#components'
  match 'content' => 'presentation#content'
  match 'build'  => 'presentation#build'
  match 'images_background'  => 'presentation#images_background'
  match 'wallpaper' => 'presentation#wallpaper'
  match 'icons'  => 'presentation#icons'
  match 'deco'  => 'presentation#deco'
  match 'editor'  => 'presentation#editor'
  match 'fonts'  => 'presentation#fonts'
  match 'fontssize'  => 'presentation#fontssize'

  resources :users
  resources :sessions
  resources :password_resets
  

  post '/presentation/new', to: 'presentation#new'
  post '/presentation/:id/edit', to: 'presentation#edit'

  resources :presentation do
    post '/content', to: 'presentation#content'
    post '/:id/content', to: 'presentation#content'
  end

  

  root :to => 'presentation#dashboard'

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  attr_accessible :data, :name
  belongs_to :user
end

app/controllers/presentation_controller.rb
require 'zip'

class PresentationController < ApplicationController
  layout "application", except: [:build]
  before_filter :load_presentation_from_params, only: %w(content download update new)
  before_filter :load_presentation_from_database, only: %w(show edit)

  def new
  end

  def new_prez
    load_presentation_from_params
  end

  def create
    if logged_in?
      presentation = current_user.presentations.create data: params.to_yaml, name: params[:name]
      redirect_to edit_presentation_path(presentation)
    end
  end

  def edit
    render action: :new
  end
  
  def destroy
    current_presentation.destroy
    redirect_to build_path(p, anchor: 'pres-listing')
  end

  def show
    render action: :new
  end

  def list
    @presentations = current_user.presentations
  end

  def update
    current_presentation.update_attributes(data: params.to_yaml, name: params[:name])
    render action: :new
  end

  def build
    if logged_in?
      @presentations = current_user.presentations
    end
    @user = User.new
  end

  def dashboard
  end

  def images_background
  end

  def wallpaper
  end

  def icons
  end

  def fonts
  end

  def fontssize
  end

  def deco
  end

  def components
  end

  def editor
  end

  def content
  end

  def download
    data = render_to_string :new
    data.gsub!('<script src="/', '<script src="./')
    data.gsub!('<link href="/', '<link href="./')


    js_path = Rails.root.join("vendor", "assets", "javascripts")
    css_path = Rails.root.join("vendor", "assets", "stylesheets")
    img_path = Rails.root.join("vendor", "assets", "images")

    zip = Zip::OutputStream.write_buffer do |out|
      out.put_next_entry("index.html")
      out.write(data)

      out.put_next_entry("assets/impress.js")
      out.write File.read js_path.join("impress.js")

      out.put_next_entry("assets/impress-layouts.js")
      out.write File.read js_path.join("impress-layouts.js")

      if params[:theme] == "basic"
        out.put_next_entry("assets/impress-theme1.css")
        out.write File.read css_path.join("impress-theme1.css")
      elsif params[:theme] == "blank"
        out.put_next_entry("assets/impress-theme3.css")
        out.write File.read css_path.join("impress-theme3.css")
      end

      if params[:substeps] == "false"
        out.put_next_entry("assets/navigation.js")
        out.write File.read js_path.join("navigation.js")
      else 
        out.put_next_entry("assets/substeps.css")
        out.write File.read css_path.join("substeps.css")
        out.put_next_entry("assets/substeps.js")
        out.write File.read js_path.join("substeps.js")
        out.put_next_entry("assets/navigation-substeps.js")
        out.write File.read js_path.join("navigation-substeps.js")
      end

      if params[:automated] == "true" && params[:substeps] == "false"
        out.put_next_entry("assets/automated.js")
        out.write File.read js_path.join("automated.js")
      elsif params[:automated] == "true" && params[:substeps] == "true"
        out.put_next_entry("assets/automated-substeps.js")
        out.write File.read js_path.join("automated-substeps.js") 
      end

      if params[:progress_bar] == "pbar1"
        out.put_next_entry("assets/progressbar.css")
        out.write File.read css_path.join("progressbar.css")
        out.put_next_entry("assets/progressbar.js")
        out.write File.read js_path.join("progressbar.js") 
      end        
    end
    zip.rewind
    binary_zip = zip.sysread

    send_data(binary_zip, {filename: "impress-customized.zip"})
  end

  private
  def load_presentation_from_params
    @id = params[:id]
    @num_slides = 8
    @num_slides = params[:num_slides].to_i if params[:num_slides].to_i > 0
    @layout = "vertical"
    @layout = params[:layout] if ["vertical", "random", "linear", "circlev1", "circlev2", "circlev3", "circlev4", "chain", "lineargrid", "snakegrid", "verticalgrid", "deep"].include?(params[:layout])

    if params[:shape] == "circle"
      @shape_class = "slide-circle"
    else 
      @shape_class = ""
    end
    @automated = "false"
    @automated = params[:automated] if ["false", "true"].include?(params[:automated])
    @theme = "basic"
    @theme = params[:theme] if ["basic", "blank"].include?(params[:theme])
    @substeps = "true"
    @substeps = params[:substeps] if ["false", "true"].include?(params[:substeps])
    @progress_bar = "no-pbar"
    @progress_bar = params[:progress_bar] if ["no-pbar", "pbar1"].include?(params[:progress_bar])

    @example_slides = %w{title ollist ullist paragraph substeps blockquote align colors}
    @content = params[:content]
    @background = params[:background] 
    @wallpaper = params[:wallpaper] 
    @text = params[:text]
    @imageNum = params[:imageNum]
    @name = params[:name]
    @shape = params[:shape]
  end

  def load_presentation_from_database
    @id = current_presentation.id
    @num_slides = presentation_data[:num_slides].to_i
    @layout =  presentation_data[:layout]
    if presentation_data[:shape] == "rectangle"
      @shape_class = "slide"
    elsif presentation_data[:shape] == "circle"
      @shape_class = "slide-circle"
    else 
      @shape_class = ""
    end
    @automated =  presentation_data[:automated]
    @theme =  presentation_data[:theme]
    @substeps =  presentation_data[:substeps]
    @progress_bar =  presentation_data[:progress_bar]
    @example_slides =  presentation_data[:example_slides] || %w{title ollist ullist paragraph substeps blockquote align colors}
    @content =  presentation_data[:content]
    @background =  presentation_data[:background]
    @wallpaper =  presentation_data[:wallpaper]
    @text =  presentation_data[:text]
    @imageNum = presentation_data[:imageNum]
    @name = presentation_data[:name]
    @shape = presentation_data[:shape]
  end
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/views/presentation/partials/_align.html.erb
 <h2> Text Align Classes</h2>
   <br/>
          <p class="text-left">Left aligned text.</p>
          <p class="text-center">Center aligned text.</p>
          <p class="text-right">Right aligned text.</p>

app/views/presentation/partials/_blockquote.html.erb
  <blockquote>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget leo nunc, nec tempus mi? Curabitur id nisl mi, ut vulputate urna!
          <cite>Somebody famous</cite>
          </blockquote>

app/views/presentation/partials/_colors.html.erb
 
<h2> Color Classes </h2>
  <br/>
 <p class="green">This is text with class="green"</p>
          <p class="red">This is text with class="red"</p>
          <p class="grey">This is text with class="grey"</p>
          <p class="orange">This is text with class="orange"</p>
          <p class="blue">This is text with class="blue"</p>

app/views/presentation/partials/_list.html.erb
  

  <nav class="main-nav" id="pres-listing">
    <div class="close">
      <a href="#" id="close-listing"> ☰ </a>
    </div>
    <% @presentations.each do |p| %> 

    <div class="row-name">
     <%= link_to  p.name, edit_presentation_path(p), {target: "preview", :class=> "name" } %>
     <%= link_to raw('<i class="icon-laptop "></i>'), presentation_path(p), {target: "_blank", :class => '' }  %>
     <%= link_to raw('<i class="icon-remove"></i>'), p, confirm: 'Are you sure?', method: :delete, :class => 'remove' %>

    </div>

    <% end %>
      <div class="new">
        <%= link_to "New", method: :new %>
     </div>


</nav>

app/views/presentation/partials/_ollist.html.erb
<h2>Agenda</h2>
  <br/>
<ol>
<li>Lorem ipsum dolor</li>
<li>Lorem ipsum dolor</li>
<li>Lorem ipsum dolor</li>
<li>Lorem ipsum dolor </li>
</ol>

app/views/presentation/partials/_paragraph.html.erb
 <h2>Paragraph</h2>
   <br/>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
     tempor incididunt ut labore et dolore magna aliqua.</p> 
    <p> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut <a> aliquip ex </a> ea commodo consequat. </p>

app/views/presentation/partials/_substeps.html.erb
   <h2>Substeps</h2>
     <br/>
            <p class="substep fadeIn"> Substep fadeIn </p>
            <p class="substep fadeInRight" > Substep fadeInRight</p>
            <p class="substep fadeInLeft"> Substep  fadeInLeft</p>
            <p class="substep rollIn" > Substep rollIn </p>
            <p class="substep flipInX" > Substep flipInX </p>

app/views/presentation/partials/_title.html.erb
<br/>
<h1 class="example">Imprez.co</h1>
<h2>Proudly presents:</h2>
<h2>The most impressive presentation tool</h2>

app/views/presentation/partials/_ullist.html.erb
   <h2>Good to know</h2>
   <br/>
          <ul>
          <li>Lorem ipsum dolor</li>
          <li>Lorem ipsum dolor</li>
          <li>Lorem ipsum dolor</li>
          <li>Lorem ipsum dolor </li>
          </ul>